# Generated by Django 4.2.7 on 2023-11-08 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='profile_pic',
            field=models.ImageField(default=True, upload_to='students'),
            preserve_default=False,
        ),
    ]
